name: colorado-job-tracker
type: python:3.11

web:
  commands:
    start: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"

disk: 1024

mounts:
  'data':
    source: local
    source_path: data
